### PR TITLE
Revert "Remove bok-choy references"

### PR DESCRIPTION
**Pull request by timmc-edx**
Reverts openedx/edx-tools#40 to restore automatically generated CSV files. We should either re-run whatever scripts generated the CSV or leave them alone as a historical record.

@salman2013 @feanil

### CODE REVIEW

**Comment by feanil** [comment]
@timmc-edx why does this need to be reverted?  Is this data referenced somewhere?

**Comment by timmc-edx** [comment]
I don't recall the details, but I had occasion to look in one of the CSV files and the columns were messed up. I'd prefer that the  entire file be either left untouched or deleted outright rather than removing some columns from some rows.

**Comment by feanil** [comment]
@timmc-edx can you provide any more details? I juts looked through the tools in this repo and it looks like most of them are ancient and no longer relevant.  I'm gonna put this repo through the deprecation process rather than fix it up.

**Comment by feanil** [comment]
Deprecation ticket here: https://github.com/openedx/edx-tools/issues/43

**Comment by feanil** [comment]
That said, I'm good to merge this so that the data is less mangled in the archived repo. And since it's gonna come out of the org I'm fine with it mentioning other old tech.

**Review by feanil — APPROVED** [review]

**Comment by timmc-edx** [comment]
Sounds good!

**Pull request merged**
